### ISSUE TITLE
Dynamic settings

### ISSUE THREAD

**Issue by Stargirl-chan** [TheTerminalCafe/ttc-bot#12]
Rather than settings options being set in a config.yaml file, we should implement a setting system where settings are stored in a DB.
This allows us to dynamically change specific options (channel blacklists, welcome messages, etc) from within discord, rather than needing to log into the server and edit the config file.

**Comment by Kirottu** [comment]
Yes, this could be done with either storing the config inside the program and updating it or with the database, database probably being the more extensible option allowing for external configuration edits.

**Comment by Kirottu** [comment]
Dynamic settings have been implemented on my development branch.
