### ISSUE TITLE
Editing a message may remove embedded ping

### ISSUE THREAD

**Issue by Glitched519** [TheTerminalCafe/ttc-bot#13]
In the logs for message edit, two messages were edited, but did not maintain their embed ping within the logging (in the image).

![image](https://user-images.githubusercontent.com/33491861/146079686-709dc907-9425-4f31-9638-20e652965b9f.png)

**Comment by Kirottu** [comment]
Probably an issue with how the update events are currently parsed, getting the new message content with an http request should probably help with this issue.

**Comment by Kirottu** [comment]
This should be fixed up by now by getting the message from the api instead of relying on the event info.
