### ISSUE TITLE
translation error when translating a message with #

### ISSUE THREAD

**Issue by ubermaister** [TheTerminalCafe/ttc-bot#60]
As stated in the title translating a message that contains a "#" will absolutely fuck up and end the translation.
for instance if you try to translate a message "*miten menee #kirottu muoto*" and it will only translate "*miten menee.*" 

here the bots sent message with that input: https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl={en}&dt=t&q={miten%20menee%20#kirottu%20muoto} and it will print to file as *"{how's it going","{miten menee"*

but with a small change to the input url by changing the "#" with "%23" in the url you get: *"{how's it going #cursedshape}","{miten menee #kirottu muoto}"*

**Comment by ghost** [comment]
PR has been opened for a potential fix.
